backend:
  name: github
  repo: RajeevG96/hugo-tutorial # Path to your Github repository
  branch: master # Branch to update

media_folder: "src/img/gallery" # Media files will be stored in the repo under images/uploads

collections:
  - name: food
    label: "Food Item" # UI (CMS)
    folder: "site/content/food"
    create: true # Users can create new docs in this collection
    fields: # The fields each document in this collection have
    - {label: "Food Item", name: "title", widget: "string"}
    - {label: "Supported Meals", name: "categories", widget: "list", default: ["breakfast", "lunch", "dinner"]}
    - {label: "Ingredients/Description", name: "description", widget: "text"}
    - {label: "Type of Food", name: "type", widget: "raw bar"}
    - {label: "Price", name: "price", widget: "string"}
